### ISSUE TITLE
Remove support for `babel-eslint`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#1040]
It's [not maintained anymore](https://github.com/babel/babel-eslint), so I don't think it makes sense for us to support it.

- [ ] Document that `babel-eslint` is not supported.
- [x] Remove `test.babelLegacy()`.
- [ ] Detect and throw at runtime?
- [ ] Remove workarounds that are fixed in `@babel/eslint-parser`, like: https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1036/files#diff-66bd496c5747eb2ce80ffc1d5e923d08c0bc538e37af77e1078e106e992d7a4aR11-R13, and [`ExperimentalRestProperty` node](https://github.com/sindresorhus/eslint-plugin-unicorn/search?q=ExperimentalRestProperty)

I think we can do `1` right now, and do the rest a little bit later on to give people time to migrate.

@fisker Thoughts?

**Comment by fisker** [comment]
In my experience, 

1. `babel-eslint` is still very popular, people don't even know there is a new one.
2. `@babel/eslint-parser` is hard to config.

I think it's still too early to remove support for `babel-eslint`.

**Comment by sindresorhus** [comment]
We should at least document that `@babel/eslint-parser` is recommended to make people aware.

**Comment by fisker** [comment]
Sure.

**Comment by fisker** [comment]
- Document that babel-eslint is not supported.

`babel-eslint` already have show deprecated message when installing, https://github.com/babel/babel/discussions/12702

- Detect and throw at runtime?

I don't think it's necessary.

 Remove workarounds that are fixed in @babel/eslint-parser, like: #1036 (files), and ExperimentalRestProperty node

`ExperimentalRestProperty` removed in #1211, but that workaround is still an issue, I'll report to the new repo.
