### ISSUE TITLE
`no-array-reduce` should not apply where it's not easily replaceable (objects, JSX)

### ISSUE THREAD

**Issue by fregante** [sindresorhus/eslint-plugin-unicorn#1379]
Applying the rule on this code would mean either adding an IIFE with a for-of loop inside or splitting the object declaration from the application (which requires assertions or dead code in TypeScript)

I think this would be a similar exception to #1348 (of which this issue might be a slight duplicate)

```jsx
return {
	huge: 'object',
	with: 'many',
	keys: array.reduce(etc)
};
```

```jsx
<Display>
	<Title>{title}</Title>
	<Modal>
		<List>{array.reduce(reducer)}</List>
	</Modal>
</Display>
```

**Comment by fisker** [comment]
DoExpression?

**Comment by sindresorhus** [comment]
I don't see how this code changes the argument of the rule for when "reduce" is bad.

---

> I think this would be a similar exception to #1348 (of which this issue might be a slight duplicate)

It's not. That case is for when "reduce" is actually appropriate; for summing.

**Comment by chasm** [comment]
This is a remarkably stupid rule. Instead of simply teaching programmers to use `reduce` well, just ban it entirely. If you can replace it with `map`, then you are using it wrongly. If you can replace it with `filter`, then you are using it wrongly. And there is no reason to believe that those who use `for-of` instead will write any more intelligible code.

This rule is patronizing and rude. These rules should help discern good usage from poor usage, not tell me what I can or cannot use.

**Comment by sindresorhus** [comment]
> Instead of simply teaching programmers to use reduce well, just ban it entirely.

There's only so much we can do with static analysis. We do intend to add exceptions when using `reduce` actually makes sense, like in https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1348.

> This rule is patronizing and rude.

The rule is deeply sorry for having offended you.

> not tell me what I can or cannot use.

You're not forced to use the rule (at least not by us). You can turn it off.

**Comment by fregante** [comment]
> These rules should help discern good usage from poor usage

What is a good usage of .reduce()?

**Comment by chasm** [comment]
First, when you have a rule that you can't measure correctly, then the right way to do it is to allow users to **opt in** rather than forcing them to opt out. 

Second, when you create a library, especially a library of "rules" for others to follow to ensure that their code is "good" code, then you appoint yourself as arbiter of "good" code. Many impressionable new developers (and even some experienced ones) will take as a given your "authority" to make these decisions.

So when you create a rule that says, effectively, "reduce is bad", then you are telling developers that they should eliminate this tool from their toolkit. In my view, that's not only irresponsible, it's reprehensible.

If `map` and `filter` are useful functions, then why not `reduce`? Reduce is nothing more than a higher abstraction. Where `map` and `filter` supply the return value -- another array -- `reduce` permits you to supply your own. And it can be _anything:_ a number, an array, an object, a boolean, a string -- even undefined or null.

As a consequence, we can use `reduce` to create the `map` function and the `filter` function and all the others, but we cannot re-create `reduce` with the `map` or `filter` functions.

An important idea to teach to new developers is that abstraction is about _power_, and we should always use the _least power_ required to accomplish the objective. So _most_ of the time, `map`, `filter`, `find`, `sort`, etc. will do the job well enough. Better, in fact, because they are a _lower form of abstraction_.

But when you have an instance where _more_ abstraction is needed, then `reduce` is an excellent choice. What an absurd notion that it's only good for summing numbers! And despite your snarky comment, it is not the "rule" that created this nonsense, it's you, the authors of this library. The rule didn't write itself.

I see no reason to claim that `for-of` is any more likely to produce readable code and you provide zero evidence to support it. In my experience, what `for-of` generally does is to introduce mutability and/or side effects where none are needed. This preference for `for-of` leads me to suspect that the authors of this library are dyed-in-the-wool OO programmers and not really comfortable with FP, which makes them utterly unsuited to giving advice to anyone regarding FP constructs, IMO.

`for-of` has the added problem of regularly being confused with `for-in`. In fact, I have to look it up every time, but then I prefer `reduce`.

Most people who struggle with `reduce` have, in my experience (and I teach programming), never had it properly explained to them. If you've never understood it, then of course you're going to write terrible code. But those who can't write a good `reduce` probably can't write a good `for-of` either. The solution isn't to banish `reduce`, but to teach people to write better code.

Understanding `reduce` is easy. It is essentially `map` or `filter` or any of the other functions that loop over an array and return something new, except that _you get to decide what gets returned_. You give reduce some kind of "bucket" and with each loop you are given an item from the array _and the bucket_. And you get to decide what, if anything, to put in the bucket and what, if anything, to do to it first.

So, for example, I can replicate `map` easily:

```js
function map(fn, arr) {
  function innerMap(arr) {
    return arr.reduce((acc, item) => [...acc, fn(item)], [])
  }
  
  return arr ? innerMap(arr) : innerMap
}

map(x => x * 2, [1, 2, 3, 4, 5]) // [ 2, 4, 6, 8, 10 ]
map(x => x * 2)([1, 2, 3, 4, 5]) // [ 2, 4, 6, 8, 10 ]
```

This is arguably better than the built-in `map` method because it is curried so it can be partially applied, unlike the method. I used `reduce`, but I could have wrapped the `map` method itself just as easily, and that would probably be better here because the `reduce` is more powerful than it needs to be. And yes, this is a fairly naïve implementation. The point is simply that `reduce` can do `map`, but `map` can't do `reduce`. Hence, `reduce` is more powerful.

`filter` and all the rest can be done the same way. In fact, I _teach_ functional programming in part by having the learner write all the common functions—`map`, `filter`, etc.—first with recursion and/or `reduce`. In the process, they learn how powerful `reduce` is as well as how those functions really work. And they learn to respect the power of abstraction and use it wisely and frugally.

What's a good use for `reduce`? How about any time I want to pass back more information than merely the nominal return value, e.g. metadata. Maybe I'm parsing through a long document and I want to return the word count, the character count, etc. alongside the parsed output. Reduce can do that easily.

Or any time I want to "fold" values into themselves. This isn't limited to numbers. I can use `reduce` as a string builder as easily.

Or any time I want to do multiple operations in a single pass:

```js
const colors = ['red', 'Yellow', 'GREEN', 'cYaN', 'blue', 'MagentA']

colors.filter((color) => color.length > 4).map((color) => color.toUpperCase()) // 1.5 passes

colors.reduce((acc, color) => color.length > 4 ? [...acc, color.toUpperCase()] : acc, []) // 1 pass
```

Is the second example really so difficult to understand that it's worth that extra pass to do the former?

What if I want to create a `pick` function? Yeah I can do this with a mix of `Object.keys` and `filter` and some recursion, but would that really be any simpler? Here you loop through the keys you want (I even allow paths). If the key exists, you add it to the bucket. If it's a path, you recurse down the path and _then_ add it to the bucket. You return the bucket. Easy peasy.

```js
const s1 = 'w'
const s2 = 'x.y.z'
const a1 = ['a']
const a2 = ['b', 'c', 'd']
const paths = [a1, s2, s1, a2]

const obj = {
  a: 'A',
  b: {
    c: {
      d: 'B.C.D',
      e: 'E'
    },
  },
  p: {
    q: 'P.Q',
  },
  r: 'R',
  w: 'W',
  x: {
    y: {
      z: 'X.Y.Z',
    },
  },
}

function pick(paths, obj) {
  const parsedPaths = paths.map((path) => Array.isArray(path) ? path : path.split('.'))

  function innerPick(obj) {
    return parsedPaths.reduce((acc, [x, ...xs]) => ({
        ...acc,
        [x]: xs.length ? pick([xs], obj[x]) : obj[x]
      }), {})
  }
  
  return obj ? innerPick(obj) : innerPick
}

pick(paths, obj)
pick(paths)(obj)

/* Both yield
  {
    a: 'A',
    x: { y: { z: 'X.Y.Z' } },
    w: 'W',
    b: { c: { d: 'B.C.D' } }
  }
*/
 
```

I typically use `reduce` in short utility functions that I write to save myself from importing an entire library for just a couple of functions. When I use them in code, as in a component, for example, I generally separate out the function and just pass it by name to `reduce`. Actually, a lot of the difficulty people encounter with `reduce` comes, IMO, from gross overuse of anonymous arrow functions. For example, it will be easier to understand the above written like this:

```js
function pick(paths, obj) {
  const parsedPaths = paths.map((path) => Array.isArray(path) ? path : path.split('.'))
  
  function recursivelyAddPathsToObject(acc, [x, ...xs]) {
    return {
      ...acc,
      [x]: xs.length ? pick([xs], obj[x]) : obj[x]
    }
  }
  
  function innerPick(obj) {
    return parsedPaths.reduce(recursivelyAddPathsToObject, {})
  }
  
  return obj ? innerPick(obj) : innerPick
}
```

That might be a little clearer. But this is just a quick pass. Anyone who understands `reduce` can no doubt come up with their own examples.

The point is, you have provided no evidence to show that `reduce` can't be written clearly and concisely, or that there is never a case where it's the best choice. You've just declared it "harmful" and discouraged anyone from even trying it.

In my view, that does your users a serious disservice, and they probably deserve more than a half-assed justification and some snarky remarks.

**Comment by fregante** [comment]
I think every single example you've given further reinforces why reduce is bad. None of your examples is particularly readable or performant. What does all that code in `pick` do? I have no idea, this is a mess:

```js
return parsedPaths.reduce((acc, [x, ...xs]) => ({
	...acc,
	[x]: xs.length ? pick([xs], obj[x]) : obj[x]
}), {})
```

and it be be probably rewritten as:

```js
const acc = {};
for (const [x, ...xs] of parsedPaths) {
	acc[x] = xs.length ? pick([xs], obj[x]) : obj[x]
}
return acc;
```

Now tell me how reduce helps that code in any way other than creating a new object in every loop.

And if you want currying, you can just use `pick.bind(null, yourFirstValue)`, without having to manually mark each function as curriable.

Clearly if you're a big FP user this plugin isn't for you, and that's ok.

You might be interested in:

- #896

**Comment by fregante** [comment]
> you have provided no evidence to show that `reduce` can't be written clearly and concisely

Check out the first line in https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-reduce.md, it points to a whole article full of such examples.

**Comment by chasm** [comment]
You must be joking, @fregante. What you are saying is simply _you don't like reduce_. So admit it. It's personal. Because I'm looking at your alternative to my example, and I can't see how it's any more readable. And look! You've introduced mutability to no purpose whatsoever As for the link, all I see is that someone named Jake Archibald hates `reduce` as much as you do.

**Comment by fregante** [comment]
> You've introduced mutability

I think that's where we diverge. You care about mutability in a self-contained piece of code, I care about readability and performance.

**Comment by sindresorhus** [comment]
I'm going to lock this now as the discussion is not directly related to the issue and it's not a productive discussion.

**Comment by fregante** [comment]
> I don't see how this code changes the argument of the rule for when "reduce" is bad.

Agreed, closing

**Comment by fisker** [comment]
I don't really understand why the argument, I disabled `no-array-reduce` myself. I also disabled some rules wrote by myself, I wrote them not because it's right, it's because someone need it.
