### ISSUE TITLE
Easy way for libraries to define deprecated methods and have them linted.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/eslint-plugin-unicorn#17]
`escodematch` like specifiers in package.json - detailing deprecated methods.

Maintainers wouldn't have to write linter rules themselves. We make it easy, and automatically scan `package.json` of dependencies to find specifiers.

**Comment by sindresorhus** [comment]
Interesting! Can you show an example of how it would look?

**Comment by sindresorhus** [comment]
Relevant: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-deprecated.md and https://github.com/benmosher/eslint-plugin-import/issues/193

**Comment by jamestalmage** [comment]
Oh wow. That's a cool way to do it.
Might be slow though. Doesn't it have to load and parse every dependency?

**Comment by sindresorhus** [comment]
@benmosher ⬆️

**Comment by benmosher** [comment]
It does parse every dependency, but if you're already using the other rules that do static analysis the plugin only parses each dependency at most once, so turning on the no-deprecated rule doesn't add much extra time.

I also wrote an ESLint memoizing parser as an experiment, to cut parse time in half by allowing ESLint proper and the import plugin to share the same parsed AST instead of each parsing their own. It helps, but doesn't even really matter until the project gets big. 

My day job application is made of about 1500 module files, IIRC, and takes ~15s to fully lint with the memo-parser.

**Comment by benmosher** [comment]
BTW, it currently uses JSDoc but could use whatever. It's not obvious to me how prevalent JSDoc is, I mostly use it internally to flag myself and others with yellow rectangles around deprecated identifiers in Sublime.

**Comment by sindresorhus** [comment]
@benmosher I assume the ESLint caching works fine with `eslint-plugin-import`?

**Comment by benmosher** [comment]
Yes and no. If you change an imported file, the files that import it won't be invalidated so if any import issues have been introduced, they won't show up. I.E.:

Module A imports B. Lint A with --cache, then delete B, then re-lint A with --cache. I would expect it not to report B as missing since A's content still matches the last lint execution. I am not super-familiar with ESLint's caching though, so I may be wrong.

This is why I use eslint_d for faster console and Sublime linting; the in-process caches of exports default to invalidating after 30s, so an eslint_d re-lint of A would _eventually_ report B as unresolved.

**Comment by fregante** [comment]
Closing for 4 years of inactivity and because this exists:

- JavaScript: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-deprecated.md
- TypeScript: https://github.com/gund/eslint-plugin-deprecation

Reopen if unicorn needs to have its own version.
