### ISSUE TITLE
Exclude `template-indent` from `recommended` because it's unsafe

### ISSUE THREAD

**Issue by JounQin** [sindresorhus/eslint-plugin-unicorn#1869]
- https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1815#issuecomment-1126894101

- https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1868

**Comment by fregante** [comment]
If you're having issues with Prettier specifically, I suggest sending a PR to add the rule to https://github.com/prettier/eslint-config-prettier/blob/414495d420fdc3936064e86dc3a5479d60f26bd6/index.js#L143C6-L145

If there's any other specific situation, it can be discussed in detail rather than just linking to other issues.

The rule only applies to "code inside templates" and indentation generally doesn't matter there.
