### ISSUE TITLE
Performance advice on “prefer-query-selector” rule

### ISSUE THREAD

**Issue by acdha** [sindresorhus/eslint-plugin-unicorn#276]
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-query-selector.md has this claim:

> They are not faster than querySelector and it's better to be consistent.

I was curious about whether that was true and did some benchmarks, and it appears that `getElementById()` and `getElementsByClassName()` are considerably faster:

https://jsperf.com/getelementbyid-vs-queryselector/304#results

#171 didn't appear to have any benchmarks supporting this claim and it seems like something which should be cited, especially given how rapidly browser performance changes over time.

**Comment by sindresorhus** [comment]
The linked JSPerf micro-benchmark doesn't support your claim either though. It only proves that running `getElementById()` a million times for the same selector is faster. This means nothing for real-world use-cases and the benchmark is faulty as it doesn't account for selector caching. A correct micro-benchmark would use different selectors. But even then it would not represent real-world performance, where the difference is negligible.

**Comment by acdha** [comment]
Benchmarks are indeed challenging to make sure you’re measuring what your app needs but if there’s going to be a rule mentioning performance it should be based on real data. It might better to leave that out and assume that people who hit a bottleneck will disable it on key points.

**Comment by sindresorhus** [comment]
I was basing my comment on comments I've seen from people working on Blink (Chrome). I'll try to find my source for that and if I can't, I'll remove it.

**Comment by acdha** [comment]
Thanks — not trying to be difficult here but I just figure “it's better to be consistent” seems like a strong enough argument on its own (anyone who cares will need to be profiling heavily anyway).

**Comment by Alhadis** [comment]
`getElementsByClassName()` and `getElementsByTagName()` return an `HTMLCollection` object, which updates automatically when elements are added or removed from the DOM:

~~~js
const pages = document.getElementsByClassName("page");
console.log(pages.length); // 1

const newPage = Object.assign(document.createElement("div"), {className: "page"});
document.body.appendChild(newPage);
console.log(pages.length) // 2
~~~

Conversely, `querySelectorAll()` returns a static `NodeList` which does **not** reflect updates made to the DOM since instantiation. Therefore, the rule's description is misleading and should be changed.

"Consistency" is only an argument if the returned collection is referenced *once*, and done so prior to any DOM manipulation.

**Comment by MrHen** [comment]
@Alhadis I'm not seeing the connection between your comment and this issue. Did you mean to open a separate issue?

**Comment by Alhadis** [comment]
Ah right, this was specifically about the matter of performance. Sorry, that was kind of a knee-jerk reaction.

I'll open a new issue.
