### ISSUE TITLE
`expiring-todo-comments` package conditions don't work in a multi-package project layout

### ISSUE THREAD

**Issue by ark120202** [sindresorhus/eslint-plugin-unicorn#403]
Currently `expiring-todo-comments` loads `package.json` data during initial load and resolves it from working directory. However, in case of monorepo-structured project, linted files may have a closer `package.json` file. Not sure how much that would affect performance, but I think it makes sense to resolve it for every file individually.

**Comment by MrHen** [comment]
Can you post a specific example of your monorepo structure? In the monorepo structure I've used, the linting runs are always done at the project level -- not at the monorepo level.

I'm personally okay letting this be an exception but we could call it out in the documentation.

**Comment by ark120202** [comment]
Most of open source monorepos I've seen appear to use it that way:

- [Babel](https://github.com/babel/babel/blob/master/Makefile#L60)
- [Jest](https://github.com/facebook/jest/blob/master/package.json#L86)
- [Lerna](https://github.com/lerna/lerna/blob/master/package.json#L10)
- [React](https://github.com/facebook/react/blob/master/scripts/eslint/index.js#L14)
- [TypeScript ESLint](https://github.com/typescript-eslint/typescript-eslint/blob/master/package.json#L30)
- [Yarn](https://github.com/yarnpkg/yarn/blob/master/package.json#L124), [Yarn 2](https://github.com/yarnpkg/berry/blob/master/package.json#L90)

**Comment by MrHen** [comment]
Awesome, thanks for the links. I guess the repos I've maintained were cross-language so we couldn't use one tool for all of included the projects.

**Comment by happycollision** [comment]
I just ran into this problem. I actually have two use-cases within a single repo. We have a monorepo where much of the root package.json defines only the lowest-level dependencies, while other packages define very common dependencies, and leaf packages define specific dependencies.

Something like this
```
root/
  │
  ├─packages/
  │   │
  │   ├─monitor/
  │   │   │┌─────────────────┐
  │   │   └│package.json     │
  │   │    │  @sentry/browser│
  │   │    └─────────────────┘
  │   └─app/
  │       │┌─────────────────┐
  │       └│package.json     │
  │        │  @react         │
  │        │  tailwindcss    │
  │        └─────────────────┘
  │┌────────────────┐
  └│package.json    │
   │  @babel/core   │
   └────────────────┘
```

The `app` package depends on `monitor`, and both use `@babel` packages.

Inside `app`, I would have wanted to do both of the following:
1. `TODO [+@sentry/browser]: after adding sentry, we can log these errors...`
2. `TODO [+tailwindcss]: after adding tailwind, refactor away these css file imports`

The first has knowledge of a dependency in another package, which is fine in a monorepo in my opinion—especially in the comments. The second has knowledge of its own dependencies.

Neither of these work because the rule only sees the root package's dependencies (@babel, etc).

**Comment by andymac4182** [comment]
Any update on this? 
https://github.com/sindresorhus/eslint-plugin-unicorn/pull/2159 seems to resolve this. This is preventing us from adopting this check.
