### ISSUE TITLE
(v14): Make character class sorting in `regex-shorthand` optional or at least documented

### ISSUE THREAD

**Issue by brettz9** [sindresorhus/eslint-plugin-unicorn#453]
Hi,

With the latest 14.0.0, I'm getting the following false positive for `regex-shorthand` (besides those reported).

The rule is expecting sorting within character classes, though this is not advertised as being part of the rule in the docs. E.g., `/#([^)'"]+)/` can be optimized to `/#([^"')]+)/` . I think this should be either advertised as such, or, better yet, made into an option, since it is sometimes clearer to make one's own groupings without sorting, e.g., `[AaQqTt]`. 

Thanks!

**Comment by fisker** [comment]
We are using `regexp-tree` to optimize them since 14.0.0, unfortunately seems there  is no option to avoid sorting character class https://github.com/DmitrySoshnikov/regexp-tree/tree/master/src/optimizer#transforms

I guess we can document this.

**Comment by sindresorhus** [comment]
Yes, let's document it.

**Comment by brettz9** [comment]
@fisker : Thank you for the background info.

I've filed https://github.com/DmitrySoshnikov/regexp-tree/issues/199 in the hopes it may be possible to configure in the future.

**Comment by voxpelli** [comment]
I agree that this is problematic.

One part of it is that different languages sort characters in different ways. Eg. in Swedish `åäö` is last in the alphabet and in that order and this rule eg. wants to resort `åä` to `äå`. To makes matter even more complicated, German sorts those letters after their dot-less equivalents, so `ä` after `a` and `ö` after `o` – so one universal true rule is not really possible when sorting purely on letters, unless one wants to enforce a "true" sorting upon everyone else.

I've now disabled this rule on our projects, which is a pity, because it has lots of other nice things to it than the sorting.

**Comment by voxpelli** [comment]
I did find a way to deactivate character sorting @fisker, you can find it in #468

**Comment by fungiboletus** [comment]
May I suggest to disable character class sorting disabled by default ? The optimisation seems unnecessary and it makes regexps less readable.
