### ISSUE TITLE
unicorn/regex-shorthand vs eslint-plugin-optimize-regex

### ISSUE THREAD

**Issue by EvgenyOrekhov** [sindresorhus/eslint-plugin-unicorn#473]
What's the difference between `unicorn/regex-shorthand` and `optimize-regex/optimize-regex` from [eslint-plugin-optimize-regex](https://github.com/BrainMaestro/eslint-plugin-optimize-regex)?

**Comment by fisker** [comment]
currently there is not much difference for `RegexLiteral`, they are all based on `regexp-tree`

`unicorn/regex-shorthand` also optimize `RegExp` with string arguments, which `eslint-plugin-optimize-regex` doesn't.

`unicorn/regex-shorthand` disabled optimize for regex with `u` flag, because `regexp-tree` can't handle well

https://github.com/sindresorhus/eslint-plugin-unicorn/pull/437#issuecomment-554626406

https://github.com/sindresorhus/eslint-plugin-unicorn/pull/454#issue-347189863
