### ISSUE TITLE
`explicit-length-check`:  Remove `greater-than-or-equal` option

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#957]
This [option](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/explicit-length-check.md#options) force use `foo.length >= 1` when checking non-zero length, highly doubt someone prefer this.

Let's keep this open for a while to see if someone object.

Ref: https://github.com/sindresorhus/eslint-plugin-unicorn/pull/952#issuecomment-749907925

**Comment by zalanlevai** [comment]
I have just come across this issue / breaking change today, while upgrading from `34.0.1` to `36.0.0` and was unaware of the discussion around it. As you may have guessed, we were actually using this length-check style in our codebases. 😅 I was aware that not many projects were using this style, but I am still surprised by its removal.

Personally, I find this style of length-checking the most explicit and, more importantly, the most logically sound out of all available options, considering the mess that is the JavaScript `number` type. I would rather not assume any JavaScript `number` value to be an integer (`array.length > 0`), much less a positive integer (`array.length !== 0`), even if it comes from a builtin, like an array's `length` accessor. Of course, these are all just opinions and no one style is correct. But I was very glad this (admittedly niche) option existed.

Looking at the corresponding code change, I am having a hard time figuring out why it was made, as it did not seem to simplify the rule's code significantly. Was there any technical reason for its removal, or was it simply due to the assumption that it was not used by anyone? If not, is there any chance that the removal could be reverted in a future release? I would rather not have to turn off this rule to keep using this previously supported style of length-checking.

Regardless, thank you for the great work you have put into this project!

**Comment by sindresorhus** [comment]
> I would rather not assume any JavaScript number value to be an integer

The `.length` property from a built-in is always a non-negative number.

> or was it simply due to the assumption that it was not used by anyone

Not assumption. I have done open source for 10 years, I read new open source code every day, and I have never encountered this style of length checking.

> is there any chance that the removal could be reverted in a future release?

Unlikely. It's not enough that you need it. It's simply not a common enough style to warrant supporting. I also think the logical arguments behind using this style doesn't hold up.
