### ISSUE TITLE
`explicit-length-check`: Check `Set#size`

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#958]
Make [`explicit-length-check`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/explicit-length-check.md) rule work for `Set#size`

We can't tell `foo` in `foo.size` is a `Set`, but it seems safe to assume `.size` is an `integer`.

Ref: https://github.com/sindresorhus/eslint-plugin-unicorn/pull/952#issuecomment-749907925

**Comment by 0-Arngerdur-1** [comment]
I am new with JavaScript, but i would like to help with this issue. I can?

**Comment by fisker** [comment]
Go ahead.

**Comment by 0-Arngerdur-1** [comment]
Thanks, I have a question, where is the set#size rule? I already looked for it in the comment file and I can't find it.

**Comment by fisker** [comment]
[`explicit-length-check`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/explicit-length-check.md)

**Comment by 0-Arngerdur-1** [comment]
I am working on the issue, I would like to ask some questions, can I?

**Comment by 0-Arngerdur-1** [comment]
As I understand, in base of the comment in the #952, you tell two improvements for the rule "explicit-length-check" , located in the file 'eslint-plugin-unicorn/rules/explicit-length-check.js', one of these is remove the option >=1 and the other is make the rule work for Set#size. The first one I understand, if I'm not wrong, is only remove the option 'greater-than-or-equal' in the Map and in the function getLengthCheckNode. The second improve I don't understand completely well, but after analyzing it I concluded that you mean is that based on a given Set then instead of just checking non-zero, also check according of the Set values, for example, greater than 5, greater than 6 and so on. I'm right?
