### ISSUE TITLE
TypeError: source.visitorKeys[node.type] is not iterable

### ISSUE THREAD

**Issue by yoyo837** [sindresorhus/eslint-plugin-unicorn#966]
eslint-plugin-unicorn@25.0.0

`prefer-default-parameters.js:36:38`

by code:

```js
const length = quantity || 0;
```

**Comment by sindresorhus** [comment]
// @medusalix

**Comment by medusalix** [comment]
@yoyo837 I can't reproduce this on my end. Could you give a little more context about the project (e.g. eslint version, etc.)?

**Comment by yoyo837** [comment]
I'll try it.

**Comment by yoyo837** [comment]
mini code demo: [ydmap-web-cloud.zip](https://github.com/sindresorhus/eslint-plugin-unicorn/files/5802207/ydmap-web-cloud.zip)

unzip and run:
- `yarn install`
- `yarn run lint`

**Comment by medusalix** [comment]
@yoyo837 Thanks. I did some debugging and noticed that this issue was actually caused by the following line:

```js
const { genMode, quantity, seatUnit, rowsName, seatName, startFrom, ...restData } = formData;
```

It seems like ESLint considers the `...restData` to be an `ExperimentalRestProperty`, which doesn't have a corresponding entry in the `visitorKeys` map. I've fixed the issue by checking for `undefined` keys before iterating over them.

**Comment by yoyo837** [comment]
Thanks for your quick reply.
