### ISSUE TITLE
Rule proposal: `prefer-math-floor`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-unicorn#984]
Prefer `Math.floor` over "double bitwise NOT".

> It is used as a faster substitute for Math.floor() for positive numbers. It does not return the same result as Math.floor() for negative numbers, as it just chops off the part after the decimal (see other answers for examples of this). - https://stackoverflow.com/a/5971668/64949

It should be auto-fixed for positive numbers, and a suggestion for negative numbers.

## Fail

```js
~~x;
```

## Pass

```js
Math.floor(x);
```

**Comment by ricealexander** [comment]
Although `~~` is touted as an alternative to `Math.floor` the answer you link acknowledges that it isn't the same. Instead of rounding numbers down, [it truncates them](https://stackoverflow.com/questions/4055633/what-does-double-tilde-do-in-javascript/39197147#answer-27528668).

Would a more correct auto-fix for both positive and negative numbers be `Math.trunc`?

**Comment by fisker** [comment]
> Would a more correct auto-fix for both positive and negative numbers be Math.trunc?

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-math-trunc.md
